title: Wolf Code
author: Daniel du Preez
email: dan@dandupreez.tech
description: > # this means to ignore newlines until "baseurl:"
  A practice blog site created using Github Pages. Part of a course using Github Learning lab.

# social links
twitter_username: @Dan_du_Preez
github_username:  @DanDuPreez

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
